name: Forward Evaluation to Private Repo

on:
  repository_dispatch:
    types: [run-eval]
  workflow_dispatch:

jobs:
  forward_evaluation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Forward dispatch to private repo
        run: |
          echo "=== FORWARDING EVALUATION DISPATCH ==="
          echo "Event type: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Forwarding to: evaluations-internal"
          echo "====================================="
          
          # Extract client payload and forward it directly
          CLIENT_PAYLOAD='${{ toJson(github.event.client_payload) }}'
          
          echo "Client payload received:"
          echo "$CLIENT_PAYLOAD" | jq '.' || echo "Failed to parse client payload as JSON"
          
          # Forward the dispatch to the private evaluations-internal repo
          REPO_OWNER="${{ vars.PRIVATE_REPO_OWNER || 'browser-use' }}"
          TARGET_REPO="evaluations-internal"
          TARGET_URL="https://api.github.com/repos/${REPO_OWNER}/${TARGET_REPO}/dispatches"
          
          echo "🎯 Target repository: ${REPO_OWNER}/${TARGET_REPO}"
          echo "🔗 Target URL: ${TARGET_URL}"
          
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -H "User-Agent: evaluation-endpoint-forwarder/1.0" \
            "${TARGET_URL}" \
            -d "{
              \"event_type\": \"run-eval\",
              \"client_payload\": $CLIENT_PAYLOAD
            }" \
            --max-time 30 \
            --retry 3 \
            --fail-with-body || {
              echo "❌ Failed to forward dispatch to private repo"
              echo "Check that PRIVATE_REPO_TOKEN has access to the private repository"
              exit 1
            }
          
          echo "✅ Successfully forwarded evaluation dispatch to private repository"
          echo "The evaluation should now be running in evaluations-internal"

      - name: Log forwarding details
        if: always()
        run: |
          echo "=== FORWARDING SUMMARY ==="
          echo "Source: ${{ github.repository }}"
          echo "Target: evaluations-internal"
          echo "Event action: ${{ github.event.action }}"
          echo "Dispatch time: $(date -u)"
          echo "Run ID: ${{ github.run_id }}"
          echo "==========================" 